repos:
  # kernteam
  - architectuur
  - basis
  - candidate
  - documentatie
  - example
  - example-with-angular
  - gebruikersonderzoeken
  - hall-of-fame
  - icons
  - index
  - terraform
  - themes
  - wcag-statistieken
  # expertteam
  - editor
  - theme-wizard
  # community
  - denhaag
  - lux
  - mijn-services
  - rijkshuisstijl-community
  - rotterdam
  - rvo
  - tilburg
  - utrecht

npmOrgs:
  - "@amsterdam"
  - "@gemeente-denhaag"
  - "@gemeente-rotterdam"
  - "@nl-design-system"
  - "@nl-design-system-candidate"
  - "@nl-design-system-community"
  - "@nl-design-system-unstable"
  - "@nl-rvo"
  - "@rijkshuisstijl-community"
  - "@utrecht"
